# Generated by Django 5.0 on 2024-04-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productplatform',
            name='image',
        ),
    ]
